In [8]:
from statsmodels.tsa.stattools import adfuller
import pandas as pd
import numpy as np
from numpy import log
df = pd.read_csv("Dhaka Stock Exchange monthly data_f.csv")

       Date    Price      Open      High       Low Vol. Change %
0    13-Apr  3438.89  3,438.89  3,438.89  3,438.89    -   -4.21%
1    13-Mar  3590.04  3,590.04  3,590.04  3,590.04    -   -9.65%
2    20-Mar  4008.28  4,480.22  4,511.25  3,593.15    -  -10.53%
3    13-May  3878.07  3,878.07  3,878.07  3,878.07    -   12.77%
4    13-Sep  3937.68  3,937.68  3,937.68  3,937.68    -   -4.60%
..      ...      ...       ...       ...       ...  ...      ...
103  21-Dec  6756.65  6,703.25  7,055.46  6,610.17    -    0.80%
104  21-Nov  6703.25  7,000.94  7,134.75  6,699.16    -   -4.25%
105  22-Jan  7089.43  6,756.65  7,136.31  6,756.65    -    4.93%
106  21-Oct  7000.94  7,329.03  7,410.62  6,841.29    -   -4.48%
107  21-Sep  7329.03  6,869.24  7,344.05  6,869.24    -    6.69%

[108 rows x 7 columns]